language: php
php:
- 7.0

script:
# Override default Travis script action [phpunit]
- php -l *.php

branches:
  only:
  # Enable Travis hook on tags (there is regular expression for semver tag)*
  - "/\\d\\.\\d\\.\\d/"

# Enable Travis deployment
deploy:
  # Use script as a deployment tool
  provider: script
  script: sh deploy/deploy.sh
  # Restrict deployment only for tags
  on:
    tags: true

# Deployment script requires few enviromnet variables
env:
  global:
  - SVN_REPOSITORY=http://plugins.svn.wordpress.org/pmpro-fedapay-gateway
  - secure: "CMg+dbLO3TIb+qW97l5NddSFq8kn9RoETdlT3vnKoY12wQ5Tnch1gEmpSAJhfGlTswj9C7GnmxJeE21Du6TTSJ9Y/qmXCsdmc+77nca+Z9jrqKFjfbiOvhY+eJI+JvKyVPgpEA3jX60MVrchSr3eChKLT03DDSP9lm1dBgiu9xJJnYjczo9OP1CJKqmyyBo+J5jjTS97lpEMYuMP5ejiqwj4L4LzrmEtMYIhGL51YfL5uf7Q+wnoJ6aH8YXfLE31jPuH6Fnlfzbc18nW/Qvu4Zg4O8Kb7G44tKNLbnbkhS8Mg8WH7wh+tdGbWeNQyGZ8WIqzNb1uEcZhenNYNNc6F6xbpvMIXFxwKsmHox/f9V+eqFJQe0eLlVDaVVyiHuZJ6Y41zwXC+oFjt/MXx00smeFh2c6uCAffqCAjbiTClTcbaFPQjBJ/3WsWNn39ezyl+Okke8cCjqyj60RmFJU2nfP3OYkNfquQsF9lZqxGeYVE+9ydYMkMnVtSppqhBaNRL/Z5NaoI8GdNHiAasASmyQlWdbQ358fVcMWDvZqhMk7zCHzVUI8ZH3SZ0Xsqg+Fv5RMi6ZAF5dUQL+IlARJQMHAIY/XWr5DIjhce6E47XzVjDYvAiK+Xtkpuwt2QXq3yWai6MCAlLFbgIf9rVZBKnRTvpM+V7j+2iVsxuryXPAc="
  - secure: "J+/5td2mXrcWmTvZ4pk1J1qGnzUTZKDow1qO0cq7pjSXSiSnXAl1u1uh/XyAl0kGdV/gBpDpQIqlI0GsV3SbevP4+yiEBKBxfyGCgpP7dHaCo7GeS5mQFj+H+MM4NaHiRorK9Xz/LjAm0E2rCbZ/5gyuAazvarM4FVSpSsaGsM2i5JiM2y+YJbUFcCCFHT76Grcg9hF0MrZB52iTv9UVQZrlZjgB9nHOUeXW/k09KcKyopQewo9Zu06uhyVNxGZAEWL2WNxQ3BIwJwDs1I0sjxaQSO/Wt9CbC+5cbXK3T+bptZIrm+f0PVub11Y/ZnuoHVddcNL+Hh8vGPEfA5RDecrQ8RTiA72PQK/HIfKgf1ByJbGYRbPYV3xTvxbPraihEuj9WwCGZgpcPWmEwDG78SJZMLKUSLjc6g1yzESIvWB1m7gcJFWgOAjD62tqPCLoLKR+r7kgoeN9Qf4aQ5JC51HKOrzTkK2mwpaTdZWm8hbmKuYxiQpjzwzca2gEHJKg2u24gyY0mYx5lrjpl7b3E3c2rFHkPUbE2EJz8lsVspN+KLvMCwOls/LNprShFe8Pdu5q/u5CBNnFK7/8tcNUGiu86SNyhfSgzQewrAxeENsAa65TaoDPi+FidJEgqm6jMO8j3TwpjXRQGyjD5uZsLz4PCScwzLCFJEVHn+bEBO0="
